name: Deploy MultiDocker App

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker test image
        run: docker build -t multi-client-test -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true multi-client-test npm test

  push-to-dockerhub:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-client -f ./client/Dockerfile ./client
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-nginx -f ./nginx/Dockerfile ./nginx
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-server -f ./server/Dockerfile ./server
          docker build -t ${{ secrets.DOCKER_USERNAME }}/multi-worker -f ./worker/Dockerfile ./worker

          docker push ${{ secrets.DOCKER_USERNAME }}/multi-client
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-server
          docker push ${{ secrets.DOCKER_USERNAME }}/multi-worker

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate deployment package
        run: zip -r deploy.zip . -x "*.git*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          existing_bucket_name: ${{ secrets.S3_BUCKET_NAME_MULTI_DOCKER }}
